global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'component']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 30m
  receiver: 'feishu'
  routes:
    - matchers:
        - severity = critical
      receiver: 'feishu'
      group_wait: 5s
      repeat_interval: 15m

receivers:
  - name: 'feishu'
    webhook_configs:
      - url: 'http://alertmanager-feishu-bridge:5005/webhook'
        send_resolved: true
        max_alerts: 0

inhibit_rules:
  - source_matchers:
      - severity = critical
      - component = core
    target_matchers:
      - severity =~ "high|warning"
    equal: []

  - source_matchers:
      - severity = critical
      - component = firewall
    target_matchers:
      - alertname = "FirewallSnmpDown"
    equal: ['instance']
