event:
  name:
  default_layout: tournament-64-2layer

networks:
  player_vlan: 40
  wireless_vlan: 41
  player_subnets: 192.168.40.0/24
  wireless_subnets: 192.168.41.0/24
  player_gateways:
  switch_management_ranges: 192.168.10.1-100,192.168.10.254
  firewall_management_ranges:

snmp:
  community: global

devices:
  core:
    name: core
    ip: 192.168.10.254
  firewall:
    ip:
    snmp:
    unit_snmp:
  stage_switches:
    - ip: 192.168.10.11
    - ip: 192.168.10.12
    - ip: 192.168.10.13
    - ip: 192.168.10.14
  access_switches: []
  servers:
    - name: game server
      ip:

isp:
  auto_discovery: true
  max_bandwidth_mbps:
  links: []

unifi:
  enabled: false
  controller_url:
  user:
  sites: all

alerts:
  feishu_robot_token:

security:
  grafana_anonymous: true
